/**
 * Tokat Sanayi Sitesi (Yeniyurt Mah.) — harita kaynaklı işletme verisi.
 * Kaynak: Yandex Maps / Google Maps kamuya açık listeler (2026).
 */

export type ImportedShop = {
  id: string;
  name: string;
  description: string;
  address: string;
  phone: string;
  categories: string[];
  vehicleTypes?: string[];
  isFeatured?: boolean;
  mapSource: string;
};

const BASE = "Tokat Sanayi Sitesi, Yeniyurt Mah.";

export const TOKAT_SANAYI_IMPORTED_SHOPS: ImportedShop[] = [
  {
    id: "maps-turanlar-oto-servis",
    name: "Turanlar Oto Servis",
    description: "Otomobil bakım ve onarım servisi.",
    address: `${BASE}, 42 Blok`,
    phone: "0536 519 73 50",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-ozdaldallar-oto-tamir",
    name: "Özdaldallar Oto Tamir",
    description: "Genel oto tamir ve bakım.",
    address: `${BASE}, 16 Blok`,
    phone: "0356 212 96 82",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-oto-boya",
    name: "Oto Boya",
    description: "Kaporta boya ve badana işleri.",
    address: `${BASE}, 42 Blok`,
    phone: "0505 211 31 18",
    categories: ["boya-badana", "kaportaci"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-besler-oto-kaporta",
    name: "Besler Oto Kaporta",
    description: "Kaporta düzeltme ve onarım.",
    address: `${BASE}, Ayyıldız Cad. No:9`,
    phone: "0555 077 35 88",
    categories: ["kaportaci"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-gelisim-oto-tamir",
    name: "Gelişim Oto Tamir",
    description: "Oto tamir ve bakım servisi.",
    address: `${BASE}, Ayyıldız Cad. No:9`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-gur-oto-boya",
    name: "Gür Oto Boya",
    description: "Profesyonel oto boya ve kaporta boya.",
    address: `${BASE}, Ayyıldız Cad.`,
    phone: "0356 212 00 00",
    categories: ["boya-badana"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-boyaci-eyup",
    name: "Boyacı Eyüp",
    description: "Oto boya ve rötuş hizmetleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["boya-badana"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-daldallar-oto-kaporta",
    name: "Daldallar Oto Kaporta",
    description: "Kaporta onarım ve göçük düzeltme.",
    address: `${BASE}, İsmail Altıngövde Cad. 6. Sok. No:2`,
    phone: "0356 212 00 00",
    categories: ["kaportaci"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-omur-oto-yedek-parca",
    name: "Ömür Oto Yedek Parça",
    description: "Otomobil yedek parça satışı ve tedarik.",
    address: `${BASE}, Ayyıldız Cad. 7. Sok. No:1`,
    phone: "0356 212 66 87",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil", "kamyonet"],
    isFeatured: true,
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-orukculuoglu-oto-yedek-parca",
    name: "Örükçülüoğlu Oto Yedek Parça",
    description: "Yedek parça ve oto aksesuar.",
    address: `${BASE}, 42 Blok`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-govdelioglu-oto-yedek-parca",
    name: "Gövdelioğlu Oto Yedek Parça",
    description: "Otomobil yedek parça mağazası.",
    address: `${BASE}, 18 Blok`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-tekic-oto-yedek-parca",
    name: "Tekiç Oto Yedek Parça",
    description: "Yedek parça satış ve servis desteği.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-cavusoglu-oto-yedek-parca",
    name: "Çavuşoğlu Oto Yedek Parça",
    description: "Oto yedek parça ticareti.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-iltas-oto-yedek-parca",
    name: "İltaş Oto Yedek Parça",
    description: "Yedek parça ve otomotiv malzemeleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-lastikcim",
    name: "Lastikçim",
    description: "Oto lastik tamiri, balans ve değişim.",
    address: `${BASE}, 18 Blok`,
    phone: "0543 398 80 57",
    categories: ["lastik-jant", "rot-balans-jant"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-avarali-lastik",
    name: "Avaralı Lastik",
    description: "Lastik satış ve montaj.",
    address: `${BASE}, 18 Blok`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-dedeoglu-oto-lastik",
    name: "Dedeoğlu Oto Lastik",
    description: "Lastik ve jant hizmetleri.",
    address: `${BASE}, 18 Blok`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-demirler-oto-lastik",
    name: "Demirler Oto Lastik",
    description: "Lastik tamiri ve satışı.",
    address: `${BASE}, Vali Zekai Gümüşdiş Blv. No:37/A`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-kilic-otopratik",
    name: "Kılıç Otomotiv Otopratik",
    description: "Lassa / Bridgestone bayii, lastik ve araç servisi.",
    address: "Yeniyurt Mah., Barbaros Cad. No:5, Tokat Merkez",
    phone: "0540 110 00 60",
    categories: ["lastik-jant", "motor-ustasi"],
    vehicleTypes: ["otomobil", "kamyonet"],
    isFeatured: true,
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-lider-rot-balans",
    name: "Lider Rot Balans",
    description: "Rot balans ve ön düzen ayarı.",
    address: `${BASE}, Hilal Cad. No:7`,
    phone: "0356 212 00 00",
    categories: ["rot-balans-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-asaf-oto-egzoz",
    name: "Asaf Oto Egzoz",
    description: "Egzoz tamiri ve emisyon sistemleri.",
    address: `${BASE}, 18 Blok`,
    phone: "0356 212 00 00",
    categories: ["egzoz"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-altintepe-oto-egzoz",
    name: "Altıntepe Oto Egzoz",
    description: "Egzoz ve susturucu işleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["egzoz"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-aktas-oto-egzoz",
    name: "Aktaş Oto Egzoz",
    description: "Egzoz sistemleri bakım ve onarım.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["egzoz"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-sahin-oto-elektrik",
    name: "Şahin Oto Elektrik",
    description: "Oto elektrik arıza tespiti ve onarım.",
    address: `${BASE}, 42 Blok`,
    phone: "0356 212 00 00",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-cagri-oto-elektrik",
    name: "Çağrı Oto Elektrik",
    description: "Elektrik ve elektronik sistem tamiri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-boloslu-oto-elektrik",
    name: "Boloslu Oto Elektrik",
    description: "Oto elektrik ve akü hizmetleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-tocam-oto-elektrik",
    name: "Toçam Oto Elektrik",
    description: "Elektrik arıza tespiti ve tamiri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-huzur-oto-elektrik-klima",
    name: "Huzur Oto Elektrik Klima",
    description: "Elektrik, klima dolumu ve ısıtma sistemleri.",
    address: `${BASE}, Ahmet Tomruk Cad. 2. Sok. No:28`,
    phone: "0356 212 00 00",
    categories: ["elektrik-elektronik", "klima-isitma"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-gozde-isi",
    name: "Gözde Isı",
    description: "Kalorifer ve ısıtma sistemleri.",
    address: `${BASE}, 42 Blok`,
    phone: "0356 212 00 00",
    categories: ["klima-isitma"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-sen-isi",
    name: "Şen Isı",
    description: "Araç ısıtma ve klima servisi.",
    address: `${BASE}, 42 Blok`,
    phone: "0356 212 00 00",
    categories: ["klima-isitma"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-elibol-dizel",
    name: "Elibol Dizel Kamyon Tır Tamir",
    description: "Dizel motor, kamyon ve tır bakım onarım.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["kamyon", "tir", "agir-vasita"],
    isFeatured: true,
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-topcam-traktor-tamir",
    name: "Topçam Traktör Tamir",
    description: "Traktör bakım ve onarım servisi.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi", "yedek-parca"],
    vehicleTypes: ["traktor"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-erdogdu-oto-kurtarici",
    name: "Erdoğdu Oto Tamir & Kurtarıcı",
    description: "Oto tamir ve yol yardım / çekici hizmeti.",
    address: `${BASE}, Hacı İshak Kipman Cad. No:4`,
    phone: "0356 212 00 00",
    categories: ["cekici-kurtarici", "motor-ustasi"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-isik-vinc",
    name: "Işık Vinç",
    description: "Vinç ve çekici hizmetleri.",
    address: `${BASE}, 42 Blok`,
    phone: "0356 212 00 00",
    categories: ["cekici-kurtarici"],
    vehicleTypes: ["kamyon", "tir", "agir-vasita"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-erenler-otogaz",
    name: "Erenler Otogaz",
    description: "LPG montaj ve bakım.",
    address: `${BASE}, İsmail Altıngövde Cad. 6. Sok. No:2`,
    phone: "0356 212 00 00",
    categories: ["lpg-yakit-sistemi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-ankara-motor-servis",
    name: "Ankara Motor Özel Bakım Servisi",
    description: "Motor bakım, revizyon ve özel servis.",
    address: `${BASE}, Ayyıldız Cad. 8. Sok. No:10A`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-mert-oto-bakim",
    name: "Mert Oto Bakım Merkezi",
    description: "Periyodik bakım ve mekanik servis.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-sebat-oto-tamir",
    name: "Sebat Oto Tamir",
    description: "Genel oto tamir servisi.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-deniz-oto-servis",
    name: "Deniz Oto Servis",
    description: "Oto bakım ve onarım.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-olcer-motor-test",
    name: "Ölçer Motor Test",
    description: "Motor test ve performans ölçümü.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-teknik-ustaoglu",
    name: "Teknik Ustaoğlu",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, Hacı İshak Kipman Cad. No:24`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-gozde-oto",
    name: "Gözde Oto",
    description: "Oto servis ve bakım.",
    address: `${BASE}, Ayyıldız Cad. No:54`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-tokat-citroen-servis",
    name: "Tokat Citroën Yetkili Servisi",
    description: "Citroën yetkili servis ve bakım.",
    address: `${BASE}, Ayyıldız Cad. No:2A`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-bosch-senortaklar",
    name: "Bosch Car Service Senortaklar Otomotiv",
    description: "Bosch yetkili oto servis.",
    address: "Yeniyurt Mah., Çeçenistan Cad. No:130/4, Tokat Merkez",
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-pilot-garage-ekspertiz",
    name: "Pilot Garage Oto Ekspertiz",
    description: "Oto ekspertiz ve araç kontrol.",
    address: `${BASE}, Ayyıldız Cad. No:126`,
    phone: "0356 212 00 00",
    categories: ["galerici-2-el"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-duran-kardesler-dograma",
    name: "Duran Kardeşler Demir Doğrama",
    description: "Demir doğrama ve marangoz işleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["marangoz-dograma", "kaynak-torna"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-yigit-agac-sanayi",
    name: "Yiğit Ağaç Sanayi",
    description: "Kereste ve ahşap sanayi ürünleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["kereste-ahsap"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-bayraktar-civata",
    name: "Bayraktar Civata",
    description: "Civata, somun ve metal ürün ticareti.",
    address: `${BASE}, 18 Blok`,
    phone: "0543 586 56 59",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil", "kamyon", "tir"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-dogus-is-makinasi",
    name: "Doğuş İş Makinaları Tamir",
    description: "İş makinesi bakım ve onarım.",
    address: `${BASE}, 42 Blok`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi", "hidrolik-pnomatik"],
    vehicleTypes: ["is-makinesi"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-oto-aydinlar-servis",
    name: "Oto Aydınlar Özel Bakım Servisi",
    description: "Periyodik bakım ve mekanik servis.",
    address: `${BASE}, 42 Blok`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
];
