import type { ImportedShop } from "@/lib/tokat-sanayi-import";

const BASE = "Tokat Sanayi Sitesi, Yeniyurt Mah.";

/**
 * 4. tur — Ekran görüntüsündeki grid alanı (3900–3935 Sk., Gürcan Özbek, Hasan Güleroğlu, Ayyıldız)
 * Kaynak: Google Maps (2026)
 */
export const TOKAT_SANAYI_IMPORTED_SHOPS_BATCH_4: ImportedShop[] = [
  // ── Ekranda görünen işletmeler ──
  {
    id: "maps-yonel-oto-yedek-parca",
    name: "Yönel Oto Yedek Parça",
    description: "Traktör ve hafif ticari araç yedek parça satışı.",
    address: `${BASE}, Ayyıldız Cad. No:32`,
    phone: "0554 259 72 73",
    categories: ["yedek-parca"],
    vehicleTypes: ["traktor", "kamyonet", "kamyon"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-dr-ecu-chiptuning",
    name: "Dr.Ecu ChipTuning Tokat",
    description: "ECU yazılım, chip tuning ve performans optimizasyonu.",
    address: `${BASE}, Ayyıldız Cad. 8. Sk.`,
    phone: "0545 306 58 40",
    categories: ["elektrik-elektronik", "oto-kuafor-detay"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-aksoy-yapi-market",
    name: "Aksoy Yapı Market",
    description: "Yapı malzemeleri ve hırdavat satışı.",
    address: `${BASE}, Hilal Cad. No:16`,
    phone: "0356 214 40 84",
    categories: ["yapi-market-hirdavat"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-plt-yapi-jotun",
    name: "Plt Yapı — Jotun Tokat Satış Noktası",
    description: "Jotun boya ve dış cephe kaplama malzemeleri.",
    address: `${BASE}, Bosna Cad. No:27/A`,
    phone: "0356 212 56 60",
    categories: ["yapi-market-hirdavat", "boya-badana"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-onur-bufe-tekel",
    name: "Onur Büfe Tekel",
    description: "Büfe, tekel ve market.",
    address: `${BASE}, Gürcan Özbek Cad., 3916. Sk. civarı`,
    phone: "0356 212 00 00",
    categories: ["market-toptan"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-meshur-kesigin-yeri",
    name: "Meşhur Kesiğin Yeri",
    description: "Tokat usulü tepsi kebabı ve köfte restoranı.",
    address: `${BASE}, 3919. Sk. No:28`,
    phone: "0356 214 66 61",
    categories: ["restoran-yemek"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-kofteci-yusuf",
    name: "Köfteci Yusuf",
    description: "Köfte ve ızgara restoranı.",
    address: `${BASE}, Ayyıldız Cad. batı kesim`,
    phone: "0356 212 00 00",
    categories: ["restoran-yemek"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-lentina-cafe",
    name: "Lentina Cafe",
    description: "Cafe ve içecek servisi.",
    address: `${BASE}, 4048. Sk. civarı`,
    phone: "0356 212 00 00",
    categories: ["cafe-pastane"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-kekina-patisserie",
    name: "Kekina Patisserie",
    description: "Pastane ve tatlı cafe.",
    address: `${BASE}, Bosna Cad.`,
    phone: "0356 212 00 00",
    categories: ["cafe-pastane"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-gross-toptan",
    name: "Gross Toptan Perakende Satış",
    description: "Toptan ve perakende market.",
    address: `${BASE}, batı giriş`,
    phone: "0356 212 00 00",
    categories: ["market-toptan"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-all-gross",
    name: "All Gross",
    description: "Market ve gıda perakende satış.",
    address: `${BASE}, batı giriş`,
    phone: "0356 212 00 00",
    categories: ["market-toptan"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-dhl-ecommerce-tokat",
    name: "DHL eCommerce — Tokat Şubesi",
    description: "Kargo ve e-ticaret lojistik hizmeti.",
    address: `${BASE}, 4048. Sk. civarı`,
    phone: "0356 212 00 00",
    categories: ["kargo-lojistik"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-shell-sanayi",
    name: "Shell — Tokat Sanayi Sitesi",
    description: "Akaryakıt istasyonu.",
    address: `${BASE}, Ayyıldız Cad.`,
    phone: "0356 212 00 00",
    categories: ["akaryakit"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-petrol-ofisi-sanayi",
    name: "Petrol Ofisi — Tokat Sanayi Sitesi",
    description: "Akaryakıt istasyonu.",
    address: `${BASE}, Ayyıldız Cad.`,
    phone: "0356 212 00 00",
    categories: ["akaryakit"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-mng-kargo-sanayi",
    name: "MNG Kargo — Sanayi Şubesi",
    description: "Kargo ve kurye hizmeti.",
    address: `${BASE}, Mehmet Şahin Cad. 4. Sk. No:4/B`,
    phone: "0356 213 07 50",
    categories: ["kargo-lojistik"],
    mapSource: "Google Maps",
  },

  // ── Grid sokakları — oto servis & yedek parça ──
  {
    id: "maps-ars-auto-service",
    name: "Ars Auto Service",
    description: "7/24 oto bakım ve onarım servisi.",
    address: `${BASE}, Ayyıldız Cad. No:17`,
    phone: "0544 804 54 82",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-hb-oto-bakim",
    name: "HB Oto Bakım Servisi",
    description: "7/24 mekanik bakım ve tamir.",
    address: `${BASE}, Gürcan Özbek Cad. 2. Sk., 16 Blok No:5`,
    phone: "0507 554 00 75",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-yilmazlar-oto-quartz",
    name: "Yılmazlar Oto — Quartz Auto Services",
    description: "Quartz & Rubia yetkili bakım servisi.",
    address: `${BASE}, Gürcan Özbek Cad. 7. Sk.`,
    phone: "0535 592 76 30",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-cankaya-rulman",
    name: "Çankaya Rulman",
    description: "Rulman ve yedek parça satışı.",
    address: `${BASE}, Gürcan Özbek Cad. No:46`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil", "kamyon", "traktor"],
    mapSource: "Google Maps / Yandex Maps",
  },
  {
    id: "maps-cimenler-oto",
    name: "Çimenler Oto",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, 3903. Sk.`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-yasar-usta-oto",
    name: "Yaşar Usta Oto Tamir Bakım",
    description: "Mekanik tamir ve periyodik bakım.",
    address: `${BASE}, 3901. Sk. No:18`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-tokat-kesif-oto",
    name: "Tokat Keşif Oto — Motor Bakım Onarım",
    description: "Motor bakım, onarım ve yenileme.",
    address: `${BASE}, İsmail Altıngövde Cad., 3920. Sk. No:25`,
    phone: "0541 525 66 69",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-sizin-oto-ozel-servis",
    name: "Sizin Oto Özel Servis",
    description: "Özel servis bakım ve onarım.",
    address: `${BASE}, 3920. Sk. No:10`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-ca-ka-oto",
    name: "Ca & Ka Oto Bakım Servisi",
    description: "Mekanik bakım servisi.",
    address: `${BASE}, 3921. Sk.`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-beren-oto",
    name: "Beren Oto",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, 3924. Sk. No:16`,
    phone: "0535 071 13 88",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-tokat-uzmanlar-oto",
    name: "Tokat Uzmanlar Oto",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, 3916. Sk. No:4`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-sen-ortaklar-oto-bakim",
    name: "Şen Ortaklar Oto Bakım",
    description: "Mekanik bakım ve onarım.",
    address: `${BASE}, 3932. Sk.`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-sen-kardesler-oto-elektrik",
    name: "Şen Kardeşler Oto Elektrik",
    description: "Oto elektrik arıza tespiti ve onarım.",
    address: `${BASE}, 3932. Sk.`,
    phone: "0535 830 81 64",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-avsar-oto-kaporta",
    name: "Avşar Oto Kaporta Servisi",
    description: "Kaporta düzeltme ve boya hazırlık.",
    address: `${BASE}, 3933. Sk.`,
    phone: "0356 212 00 00",
    categories: ["kaportaci"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-turanlar-ozel-servis",
    name: "Turanlar Özel Servis",
    description: "Özel servis bakım ve onarım.",
    address: `${BASE}, 3933. Sk. No:26`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-dilek-oto-kaporta",
    name: "Dilek Oto Kaporta & Bakalit",
    description: "Kaporta onarım ve bakalit işleri.",
    address: `${BASE}, 3931. Sk. No:10`,
    phone: "0356 212 00 00",
    categories: ["kaportaci"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-polat-oto-tamir",
    name: "Polat Oto Tamir Bakım",
    description: "Mekanik tamir ve periyodik bakım.",
    address: `${BASE}, Ayyıldız Cad. 7. Sk. No:3`,
    phone: "0505 256 44 41",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-onder-oto",
    name: "Önder Oto",
    description: "Motor yenileme ve bakım servisi.",
    address: `${BASE}, 3939. Sk. No:15`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-bakir-oto-lastik",
    name: "Bakır Oto Lastik",
    description: "7/24 lastik tamir, satış ve yol yardımı.",
    address: `${BASE}, Sanayi girişi, İstikbal karşısı`,
    phone: "0546 439 18 43",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-merkez-oto",
    name: "Merkez Oto",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, İsmail Altıngövde Cad.`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-tia-habip-oto",
    name: "TIA Tokat Habip Oto",
    description: "Kaporta düzeltme ve boya işleri.",
    address: `${BASE}, İsmail Altıngövde Cad. No:15`,
    phone: "0536 453 72 86",
    categories: ["kaportaci", "boya-badana"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-ak-er-oto-vw",
    name: "AK-ER Oto — VW Grup & DSG Özel Servis",
    description: "Volkswagen grup bakım ve DSG onarım.",
    address: `${BASE}, Vali Zekai Gümüşdiş Blv. No:43/A`,
    phone: "0543 879 73 38",
    categories: ["motor-ustasi", "sanziman"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-fermot-arac-servisi",
    name: "Fermot Araç Servisi",
    description: "Mekanik bakım ve onarım servisi.",
    address: `${BASE}, Vali Zekai Gümüşdiş Blv. No:12/6`,
    phone: "0540 337 60 60",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-cosar-oto-lastik",
    name: "Coşar Oto Lastik",
    description: "7/24 yerinde lastik tamiri ve satış.",
    address: `${BASE}, Vali Zekai Gümüşdiş Blv. No:51`,
    phone: "0541 901 39 26",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil", "kamyonet", "kamyon"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-detay-oto-servisi",
    name: "Detay Oto Servisi",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, Mehmet Şahin Cad. No:39`,
    phone: "0541 875 12 90",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-eryil-renault-dacia",
    name: "Eryıl — Renault & Dacia Özel Servis",
    description: "Renault ve Dacia özel bakım servisi.",
    address: `${BASE}, Mehmet Şahin Cad. No:87`,
    phone: "0535 874 82 63",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-fiat-ard-auto",
    name: "Fiat Özel Servis — ARD Auto",
    description: "Fiat özel bakım ve onarım servisi.",
    address: `${BASE}, Mehmet Şahin Cad. No:37, Blok 105`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-ozgun-oto-bakim",
    name: "Özgün Oto Bakım Özel Servis",
    description: "Motor yenileme ve özel bakım.",
    address: `${BASE}, Mehmet Şahin Cad. No:55`,
    phone: "0544 841 01 60",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-topcam-ford-servis",
    name: "Topçam Oto — Özel Ford Servisi",
    description: "Ford özel bakım ve onarım servisi.",
    address: `${BASE}, Ayyıldız Cad.`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-karaca-oto-bakim",
    name: "Karaca Oto Bakım Servisi",
    description: "Mekanik bakım ve tamir.",
    address: `${BASE}, Ahmet Tomruk Cad. 4. Sk.`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-isik-oto-tamir",
    name: "Işık Oto Tamir ve Bakım",
    description: "Mekanik tamir servisi.",
    address: `${BASE}, grid alanı`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-uludag-oto",
    name: "Uludağ Oto",
    description: "Mekanik bakım ve onarım.",
    address: `${BASE}, Hilal Cad.`,
    phone: "0552 415 38 36",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-xtreme-4x4-garage",
    name: "Xtreme 4x4 Garage",
    description: "4x4 restorasyon, off-road aksesuar ve servis.",
    address: `${BASE}, Hilal Cad. No:23`,
    phone: "0549 642 00 60",
    categories: ["motor-ustasi", "oto-kuafor-detay"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-4as-otomotiv-hasar",
    name: "4 AS Otomotiv Hasar Servisi",
    description: "Hasar onarım, kaporta ve boya.",
    address: `${BASE}, grid alanı`,
    phone: "0544 532 88 24",
    categories: ["kaportaci", "boya-badana"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-rs-doganay-full",
    name: "RS Servis Doğanay Otomotiv",
    description: "Kaporta, boya, göçük, mekanik ve elektrik servisi.",
    address: `${BASE}, 3910. Sk.`,
    phone: "0532 487 41 32",
    categories: ["kaportaci", "boya-badana", "motor-ustasi", "elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
];
