import type { ImportedShop } from "@/lib/tokat-sanayi-import";

const BASE = "Tokat Sanayi Sitesi, Yeniyurt Mah.";

/** 2. tur — 18/19 Blok ve eksik işletmeler (Yandex Maps) */
export const TOKAT_SANAYI_IMPORTED_SHOPS_BATCH_2: ImportedShop[] = [
  // ── 18 Blok ──
  {
    id: "maps-bayraktar-sahinoglu",
    name: "Bayraktar Civata — Şahinoğlu Ticaret",
    description: "Civata, hırdavat ve yapı malzemeleri.",
    address: `${BASE}, 18 Blok, Gürkan Özbek Cad. No:23`,
    phone: "0543 586 56 59",
    categories: ["yedek-parca"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-silecek-sepeti",
    name: "Silecek Sepeti",
    description: "Silecek, yedek parça ve oto aksesuar.",
    address: `${BASE}, 18 Blok`,
    phone: "0543 302 55 66",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-aku-dunyasi",
    name: "Akü Dünyası",
    description: "Akü satış, değişim ve şarj cihazları.",
    address: `${BASE}, 18 Blok`,
    phone: "0546 231 87 96",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-marshall-yildizlar",
    name: "Marshall Yıldızlar Ticaret",
    description: "Lastik ve jant satışı.",
    address: `${BASE}, 18 Blok`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-ozkaya-lastik",
    name: "Özkaya Lastik",
    description: "Oto lastik tamiri ve satışı.",
    address: `${BASE}, 18 Blok`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-difoylu-oto-lastik",
    name: "Difoylu Oto Lastik",
    description: "Lastik montaj ve tamiri.",
    address: `${BASE}, 18 Blok`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-akyuzoglu-oto-aksesuar",
    name: "Akyüzoğlu Oto Aksesuar",
    description: "Oto aksesuar, ses ve görüntü sistemleri.",
    address: `${BASE}, 18 Blok`,
    phone: "0546 869 26 62",
    categories: ["oto-kuafor-detay"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-kalayci",
    name: "Kalaycı",
    description: "Kaynak ve metal işleri.",
    address: `${BASE}, 18 Blok`,
    phone: "0356 212 00 00",
    categories: ["kaynak-torna"],
    mapSource: "Yandex Maps",
  },
  // ── 19 Blok ──
  {
    id: "maps-pt-lastik",
    name: "Pt Lastik",
    description: "Lastik ve jant hizmetleri.",
    address: `${BASE}, 19 Blok`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-myk-oto-boya",
    name: "Myk Oto Boya",
    description: "Oto boya ve kaporta boya.",
    address: `${BASE}, 19 Blok`,
    phone: "0356 212 00 00",
    categories: ["boya-badana", "kaportaci"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  // ── Mobilya / Kereste bölgesi ──
  {
    id: "maps-katircioglu-kerestecilik",
    name: "Katırcıoğlu Kerestecilik",
    description: "Kereste ve ahşap malzeme satışı.",
    address: `${BASE}, Kereste Bölgesi`,
    phone: "0545 616 93 07",
    categories: ["kereste-ahsap"],
    isFeatured: true,
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-topcam-parke",
    name: "Topçam Parke",
    description: "Parke, kapı ve zemin kaplama.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["mobilya", "marangoz-dograma"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-akin-mobilya",
    name: "Akın Mobilya",
    description: "Mobilya imalat ve satış.",
    address: `${BASE}, Mobilya Bölgesi`,
    phone: "0356 212 00 00",
    categories: ["mobilya"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-sertagac-orman",
    name: "Sertağaç Sanayi Orman Ürünleri",
    description: "Orman ürünleri ve kereste ticareti.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["kereste-ahsap"],
    mapSource: "Yandex Maps",
  },
  // ── Yedek parça (ek) ──
  {
    id: "maps-sahin-oto-yedek-parca",
    name: "Şahin Oto Yedek Parça",
    description: "Otomobil yedek parça satışı.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-donmezoglu-yedek-parca",
    name: "Dönmezoğlu Oto Yedek Parça",
    description: "Yedek parça ve otomotiv malzemeleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-cingilli-otomotiv",
    name: "Cıngıllı Otomotiv",
    description: "Otomotiv yedek parça ve servis.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca", "motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-ates-otomotiv",
    name: "Ateş Otomotiv",
    description: "Yedek parça ve oto servis.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-oncul-ticaret",
    name: "Öncül Ticaret",
    description: "Oto yedek parça ticareti.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-ekmekcioglu-otomotiv",
    name: "Ekmekçioğlu Otomotiv",
    description: "Yedek parça ve otomotiv ürünleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-kircaer-motor-yedek",
    name: "Kırcaer Motor Yedek Parça",
    description: "Motor yedek parça ve yetkili servis.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca", "motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-star-oto-market",
    name: "Star Oto Market",
    description: "Oto aksesuar ve yedek parça marketi.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca", "oto-kuafor-detay"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-mobil-1-center",
    name: "Mobil 1 Center",
    description: "Motor yağı ve bakım ürünleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  // ── Lastik / rot (ek) ──
  {
    id: "maps-topcam-oto-lastik",
    name: "Topçam Oto Lastik",
    description: "7/24 lastik servisi.",
    address: `${BASE}, Ayyıldız Cad. 7. Sok. No:20`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-doktor-oto-lastik",
    name: "Doktor Oto Lastik",
    description: "Lastik tamiri ve acil servis.",
    address: `${BASE}, Ayyıldız Cad. 7. Sok. No:2`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-lastigim-zaman",
    name: "Lastiğim — Zaman Otomotiv",
    description: "Lastik ve jant satışı.",
    address: `${BASE}, Ayyıldız Cad. No:148`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-uzman-rotbalans",
    name: "Uzman Rotbalans Lastik",
    description: "Rot balans, lastik ve çekici hizmeti.",
    address: `${BASE}, Hacı İshak Kipman Cad. No:30`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant", "rot-balans-jant", "cekici-kurtarici"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-petlas-tokat",
    name: "Petlas Tokat",
    description: "Petlas lastik bayii.",
    address: `${BASE}, Ayyıldız Cad. No:45/B`,
    phone: "0356 212 00 00",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-yildiz-rot-balans",
    name: "Yıldız Rot Balans",
    description: "Rot balans ve lastik hizmetleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["rot-balans-jant"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  // ── Servis (ek) ──
  {
    id: "maps-rs-servis",
    name: "RS Servis",
    description: "Oto bakım ve onarım servisi.",
    address: `${BASE}, Hilal 1. Sok. No:1`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-alp-oto",
    name: "Alp Oto",
    description: "Otomobil servis ve bakım.",
    address: `${BASE}, Ayyıldız Cad. No:104`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-cozum-otomotiv",
    name: "Çözüm Otomotiv",
    description: "Genel oto servis ve bakım.",
    address: `${BASE}, Hilal Cad. No:30`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-kariyer-oto",
    name: "Kariyer Oto",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, Gürkan Özbek Cad. 7. Sok. No:14`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-akgun-oto-tamir",
    name: "Akgün Oto Tamir",
    description: "Oto tamir servisi.",
    address: `${BASE}, İsmail Altıngövde Cad. No:14`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-eurorepar",
    name: "Eurorepar",
    description: "Eurorepar yetkili oto servis.",
    address: `${BASE}, 3903. Sok. No:12`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-oto-yarbac",
    name: "Oto Yarbaç",
    description: "Oto servis ve bakım.",
    address: `${BASE}, İsmail Altıngövde Cad. No:93`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-sm-oto-servis",
    name: "SM Oto Servis",
    description: "Otomobil bakım servisi.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-tokat-otomatik-sanziman",
    name: "Tokat Otomatik Şanzıman",
    description: "Otomatik şanzıman tamiri ve bakımı.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["sanziman"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-fener-motor-yenileme",
    name: "Fener Motor Yenileme",
    description: "Motor revizyon ve yenileme.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  // ── Traktör / galeri ──
  {
    id: "maps-ls-traktor",
    name: "LS Traktör",
    description: "Traktör satış ve servis.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["yedek-parca"],
    vehicleTypes: ["traktor"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-ugur-traktor-galeri",
    name: "Uğur Traktör Galeri",
    description: "Traktör galeri ve satış.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["galerici-2-el"],
    vehicleTypes: ["traktor"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-okan-galeri",
    name: "Okan Galeri",
    description: "İkinci el araç galerisi.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["galerici-2-el"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  // ── Tuning / aksesuar ──
  {
    id: "maps-mert-tuning",
    name: "Mert Tuning Tokat",
    description: "Araç tuning ve performans.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["oto-kuafor-detay"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-ibo-tuning",
    name: "Ibo Tuning",
    description: "Chip tuning ve performans yazılımı.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["oto-kuafor-detay", "motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-mert-oto-aksesuar",
    name: "Mert Oto Aksesuar",
    description: "Oto aksesuar ve donanım.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["oto-kuafor-detay"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-arr-auto-sound",
    name: "Arr Auto Sound",
    description: "Oto ses ve multimedya sistemleri.",
    address: `${BASE}`,
    phone: "0356 212 00 00",
    categories: ["oto-kuafor-detay", "elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  // ── 44 Blok çevresi ──
  {
    id: "maps-arzu-bisiklet",
    name: "Arzu Bisiklet",
    description: "Bisiklet ve motosiklet tamiri.",
    address: `${BASE}, 44 Blok, İsmail Altıngövde 7. Sok. No:9`,
    phone: "0356 232 97 56",
    categories: ["motor-ustasi"],
    vehicleTypes: ["motosiklet"],
    mapSource: "Yandex Maps / Apple Maps",
  },
];
