import type { ImportedShop } from "@/lib/tokat-sanayi-import";

const BASE = "Tokat Sanayi Sitesi, Yeniyurt Mah.";

/** 3. tur — Google Maps kaynaklı yeni işletmeler (2026) */
export const TOKAT_SANAYI_IMPORTED_SHOPS_BATCH_3: ImportedShop[] = [
  {
    id: "maps-oz-auto-servis",
    name: "Öz Auto Servis",
    description: "7/24 açık oto bakım ve onarım servisi.",
    address: `${BASE}, Ayyıldız Cad. No:148`,
    phone: "0507 642 40 66",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-serdar-oto-kaporta",
    name: "Serdar Oto Kaporta",
    description: "Kaporta düzeltme ve boya hazırlık.",
    address: `${BASE}, 16 Blok`,
    phone: "0535 960 77 22",
    categories: ["kaportaci"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-ozer-oto-tamir",
    name: "Özer Oto Tamir",
    description: "Japon ve yerli araç mekanik tamir.",
    address: `${BASE}, Ahmet Tomruk Cad.`,
    phone: "0533 701 34 86",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-yildirim-oto-bmw-mercedes",
    name: "Yıldırım Oto — BMW & Mercedes Özel Servis",
    description: "BMW ve Mercedes özel bakım ve onarım.",
    address: `${BASE}, Hacı İshak Kipman Cad., 3931. Sk. No:22`,
    phone: "0555 962 58 22",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-tokat-oto-anahtar-cilingir",
    name: "Tokat Oto Anahtar & Çilingir",
    description: "Oto anahtar, immobilizer ve çilingir hizmeti.",
    address: `${BASE}, 3924. Sk. No:2`,
    phone: "0545 607 60 60",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-sahin-oto-eurorepar",
    name: "Eurorepar Şahin Oto Servis",
    description: "Eurorepar yetkili mekanik servis.",
    address: `${BASE}, Ayyıldız Cad. No:50`,
    phone: "0533 396 25 80",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-onler-oto-makyaj",
    name: "Önler Oto Makyaj",
    description: "Araç kaplama ve estetik uygulamalar.",
    address: `${BASE}, Çeçenistan Cad. No:117`,
    phone: "0505 037 83 36",
    categories: ["oto-kuafor-detay"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-tek-oto-citroen-peugeot",
    name: "Tek Oto — Citroën & Peugeot Özel Servis",
    description: "Citroën ve Peugeot özel bakım servisi.",
    address: `${BASE}, Acenteler Blok 31/B, Vali Zekai Gümüşdiş Blv.`,
    phone: "0544 229 52 79",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-kel-huseyin-kilitci",
    name: "Kel Hüseyin Kilitçi",
    description: "Oto kilit, anahtar ve güvenlik sistemleri.",
    address: `${BASE}, Ek Sanayi Sitesi 43 Blok No:225`,
    phone: "0554 371 05 54",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-mert-oto-elektrik",
    name: "Mert Oto Elektrik",
    description: "7/24 oto elektrik arıza tespiti ve onarım.",
    address: `${BASE}, Ayyıldız Cad. No:74`,
    phone: "0545 811 18 66",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-mega-oto-kaporta",
    name: "Mega Oto Kaporta Tokat",
    description: "Kaporta onarım ve göçük düzeltme.",
    address: `${BASE}, Ek Sanayi Sitesi 48 Blok, Ahmet Tomruk Cad. 3. Sk. No:18`,
    phone: "0537 600 32 87",
    categories: ["kaportaci"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-onur-oto-motrio",
    name: "Onur Oto — Motrio Renault & Dacia Servis",
    description: "Renault ve Dacia Motrio özel bakım servisi.",
    address: `${BASE}, Vali Zekai Gümüşdiş Blv. No:31`,
    phone: "0543 935 26 45",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-suer-oto-nusurler",
    name: "Süer Oto (Nüşürler Garage)",
    description: "Mekanik tamir ve periyodik bakım.",
    address: `${BASE}, Ek Sanayi Sitesi 41 Blok`,
    phone: "0541 678 90 33",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-safir-otomotiv",
    name: "Safir Otomotiv",
    description: "Orijinal parça ile bakım ve onarım.",
    address: `${BASE}, Gürkan Özbek Cad.`,
    phone: "0549 213 01 00",
    categories: ["motor-ustasi", "yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-uluhan-isuzu",
    name: "Uluhan Isuzu",
    description: "Isuzu kamyon ve ticari araç servisi.",
    address: `${BASE}, 17 Blok No:11`,
    phone: "0356 214 04 75",
    categories: ["motor-ustasi"],
    vehicleTypes: ["kamyon", "kamyonet", "agir-vasita"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-es-oto-tamir",
    name: "Es Oto Tamir ve Bakım",
    description: "Genel oto tamir ve bakım atölyesi.",
    address: `${BASE}, 3923. Sk. No:15`,
    phone: "0546 910 35 77",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-korkmaz-oto",
    name: "Korkmaz Oto",
    description: "Mekanik tamir ve bakım servisi.",
    address: `${BASE}, Ek Sanayi Sitesi 47 Blok No:17`,
    phone: "0531 233 90 23",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-boyaci-atilla-ogullari",
    name: "Boyacı Atilla ve Oğulları",
    description: "Fırınlı boya ve kaporta boya işleri.",
    address: `${BASE}, Ek Sanayi Sitesi 47 Blok No:323`,
    phone: "0552 334 33 60",
    categories: ["boya-badana"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-ozkan-oto-lastik",
    name: "Özkan Oto Lastik",
    description: "7/24 lastik satış, tamir ve balans.",
    address: `${BASE}, 36 Blok No:18`,
    phone: "0543 913 61 98",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-krd-auto-detailing",
    name: "KRD Auto Detailing",
    description: "Detaylı iç-dış temizlik ve koruma uygulamaları.",
    address: `${BASE}, 18 Blok, Kesik Usta arası`,
    phone: "0537 476 45 22",
    categories: ["oto-kuafor-detay"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-celik-oto-service",
    name: "Çelik Oto Service",
    description: "Mekanik tamir, motor ve şanzıman bakımı.",
    address: `${BASE}, 23 Blok, Gürkan Özbek Cad. 7. Sk. No:10`,
    phone: "0505 096 05 60",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-gunduz-otogaz",
    name: "Gündüz Otogaz Atiker Prins",
    description: "LPG dönüşüm, bakım ve egzoz muayenesi.",
    address: `${BASE}, Ek Sanayi Sitesi, Hasan Güleroğlu No:15`,
    phone: "0549 550 50 21",
    categories: ["lpg-yakit-sistemi", "egzoz"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-salihoglu-michelin",
    name: "Salihoğlu Ticaret — Michelin",
    description: "Michelin yetkili lastik satış ve servis.",
    address: `${BASE}, Acenteler Blok, Ayyıldız Cad.`,
    phone: "0356 214 12 42",
    categories: ["lastik-jant"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-ileri-traktor",
    name: "İleri Traktör",
    description: "Traktör tamir, bakım ve yedek parça.",
    address: `${BASE}, 22 Blok No:64`,
    phone: "0538 408 31 78",
    categories: ["motor-ustasi", "yedek-parca"],
    vehicleTypes: ["traktor"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-tokat-oto-elektrik",
    name: "Tokat Oto Elektrik",
    description: "Oto elektrik tesisatı ve arıza giderme.",
    address: `${BASE}, Mehmet Şahin Bulvarı No:70`,
    phone: "0530 899 59 53",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-cesurlar-oto-elektrik",
    name: "Cesurlar Oto Elektrik",
    description: "Elektrik arıza tespiti ve onarım.",
    address: `${BASE}, 3921. Sk. No:5`,
    phone: "0549 695 00 60",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-ayaz-park-oto-yikama",
    name: "Ayaz Park Oto Yıkama & Detailing",
    description: "Detaylı yıkama ve iç temizlik.",
    address: `${BASE}, Ayyıldız Cad. No:104`,
    phone: "0544 513 56 99",
    categories: ["oto-kuafor-detay"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-tunc-oto-elektronik",
    name: "Tunç Oto Elektronik",
    description: "Oto elektrik, ECU ve yazılım işlemleri.",
    address: `${BASE}, Ayyıldız Cad. No:144`,
    phone: "0546 443 15 43",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-58-tuning-oto-market",
    name: "58 Tuning Oto Market",
    description: "Tuning, aksesuar ve oto market.",
    address: `${BASE}, Fabrikalar Blok, Hilal Cad. No:3`,
    phone: "0507 339 16 96",
    categories: ["oto-kuafor-detay", "yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-kusakoglu-kaporta-boya",
    name: "Kusakoğlu Kaporta ve Boya",
    description: "Kaporta onarım ve boya işleri.",
    address: `${BASE}, 31 Blok, Altın Gövde Cad.`,
    phone: "0543 604 43 57",
    categories: ["kaportaci", "boya-badana"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-koyluoglu-otomotiv",
    name: "Köylüoğlu Otomotiv",
    description: "Genel oto tamir ve bakım servisi.",
    address: `${BASE}, Ayyıldız Cad. No:70`,
    phone: "0356 212 91 82",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps / Yandex Maps",
  },
  {
    id: "maps-best-otomotiv",
    name: "Best Otomotiv — Opel & Chevrolet Özel Servis",
    description: "Opel ve Chevrolet özel bakım servisi.",
    address: `${BASE}, Hilal Cad.`,
    phone: "0356 212 90 95",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-sonmez-oto",
    name: "Sönmez Oto",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, Mehmet Şahin Cad.`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-kurklu-oto-egzoz",
    name: "Kürklü Oto Egzoz",
    description: "Egzoz tamiri, kaynak ve değişim.",
    address: `${BASE}, Ahmet Tomruk Cad. No:2`,
    phone: "0356 212 00 00",
    categories: ["egzoz"],
    vehicleTypes: ["otomobil", "kamyonet"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-nur-firinli-oto-boya",
    name: "Nur Fırınlı Oto Boya — Atilla Usta",
    description: "Fırınlı oto boya ve kaporta boya.",
    address: `${BASE}, Ahmet Tomruk Cad. 2. Sk. No:10`,
    phone: "0356 212 00 00",
    categories: ["boya-badana"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-celik-oto-tamir-atolyesi",
    name: "Çelik Oto Tamir Atölyesi",
    description: "Mekanik tamir ve periyodik bakım.",
    address: `${BASE}, Ahmet Tomruk Cad. 3. Sk. No:28`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-eymen-oto-ozel-servis",
    name: "Eymen Oto Özel Servis",
    description: "Özel servis bakım ve onarım.",
    address: `${BASE}, Ayyıldız Cad. 8. Sk. No:7C`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-caliskan-makina-tamir",
    name: "Çalışkan Makina Tamir",
    description: "Makine ve ağır vasıta tamir atölyesi.",
    address: `${BASE}, Hilal 3. Sk. No:1`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi", "kaynak-torna"],
    vehicleTypes: ["is-makinesi", "agir-vasita"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-erkan-usta-tamir",
    name: "Erkan Usta Tamir Atölyesi",
    description: "Mekanik tamir ve bakım.",
    address: `${BASE}, Ayyıldız Cad. 3. Sk. No:2`,
    phone: "0356 212 00 00",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
  {
    id: "maps-doganay-otomotiv",
    name: "RS — Doğanay Otomotiv",
    description: "Mekanik tamir ve bakım servisi.",
    address: `${BASE}, 3910. Sk.`,
    phone: "0542 465 00 60",
    categories: ["motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-otopratik-sensoy",
    name: "Otopratik Şensoy",
    description: "Otopratik yetkili bakım ve lastik servisi.",
    address: `${BASE}, Ayyıldız Cad. No:41/D`,
    phone: "0356 214 61 57",
    categories: ["lastik-jant", "motor-ustasi"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-mosfet-oto-elektronik",
    name: "Mosfet Oto Elektronik",
    description: "Oto elektronik, ECU ve chip tuning.",
    address: `${BASE}, Ayyıldız Cad. No:76`,
    phone: "0535 455 56 04",
    categories: ["elektrik-elektronik"],
    vehicleTypes: ["otomobil"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-hd-oto-kurtarma",
    name: "HD Oto Kurtarma Yol Yardım",
    description: "7/24 çekici ve yol yardım hizmeti.",
    address: `${BASE}, İsak Kipman Cad. 2. Geçit No:23`,
    phone: "0532 600 88 65",
    categories: ["cekici-kurtarici"],
    vehicleTypes: ["otomobil", "kamyon", "tir"],
    mapSource: "Google Maps",
  },
  {
    id: "maps-cagan-oto-set",
    name: "Çağan Oto Set",
    description: "Oto aksesuar ve set montajı.",
    address: `${BASE}, İsmail Altıngövde Cad. No:46`,
    phone: "0356 212 00 00",
    categories: ["oto-kuafor-detay", "yedek-parca"],
    vehicleTypes: ["otomobil"],
    mapSource: "Yandex Maps",
  },
];
